### ISSUE TITLE
How to determine what types to generate?

### ISSUE THREAD

**Issue by jaredramirez** [jaredramirez/border-types#2]
This is a continuation of https://discourse.elm-lang.org/t/generating-border-types/722

Basically we are not sure if we want to generate types from format (YAML, JSON, etc) that defines them, or generate them from an Elm program that exposes ports.

My preference is using something like YAML or JSON, for a few reason:
* Don't need to figure out how to use/reuse/rewrite the Elm parser to get information about the types
* Can generate type for ports **and** a server
* Types will always be in sync. If generated from ports, ports could change but the host language types might not be re-generated. If generated from a separate file, then the types will be generated for both Elm and the host language at the same time forcing them to be [in sync](https://pbs.twimg.com/media/DO18jZyUIAAjghx.jpg)

**Comment by jaredramirez** [comment]
After thinking about it, I think the best approach is using a separate system to define & generate types from. My reasoning is what I've mentioned above, plus the fact that I think it will keep the process simpler for people interested in using this tool by eliminating some of the "magic" going on behind the scenes.

**Comment by mrmurphy** [comment]
Agreed!
